# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/galisafe_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=shona1103

# Hibernate/JPA Settings (Isse tables apne aap banengi)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect